# Generated by Django 4.2.6 on 2023-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('author_surname', models.CharField(max_length=255)),
                ('genre', models.CharField(default='asedfd', max_length=255)),
                ('publication_year', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_surname', models.CharField(max_length=255)),
                ('rent_date', models.DateField()),
                ('book_title', models.CharField(max_length=255)),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
